apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: vault
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      volumes:
        - name: vault-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-vault-pvc
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8200
          volumeMounts:
            - mountPath: "/vault/data"
              name: vault-storage
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
          args:
            - "server"
            - "-dev"
