apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-vault-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/vault"
