apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8200
  type: {{ .Values.service.type }}
